export const classes = {
  breadcrumb: "mb-6",
  panel: "flex flex-col gap-3",
  stockBlock: "mt-4 space-y-3",
  descriptionStack: "mt-5 space-y-2",
  mediaFill: "h-full w-full skeleton",
  tagsRow: "mt-4 flex flex-wrap gap-2",
  priceLine: "h-8 w-28 rounded skeleton",
  stockLine: "h-4 w-32 rounded skeleton",
  actionShort: "h-10 w-28 rounded skeleton",
  categoryLine: "h-3 w-20 rounded skeleton",
  actionsRow: "mt-6 flex items-center gap-3",
  breadcrumbLine: "h-3 w-44 rounded skeleton",
  tagPill: "h-6 w-16 rounded-full skeleton",
  actionGrow: "h-10 flex-1 rounded skeleton",
  browseLine: "mt-6 h-4 w-36 rounded skeleton",
  article: "mx-auto max-w-6xl px-4 py-8 md:py-12",
  descriptionLine: "h-4 w-full rounded skeleton",
  titleLine: "h-8 w-full max-w-xl rounded skeleton",
  descriptionLineShort: "h-4 w-5/6 rounded skeleton",
  grid: "grid grid-cols-1 gap-8 md:grid-cols-2 md:gap-12",
  media:
    "relative aspect-square w-full overflow-hidden rounded-xl border border-border bg-muted",
} as const;
